namespace UnderworldManager.Models
{
  public enum Profession
  {
    Brawler,
    Runner,
    Apprentice,
    Grifter,
    Enforcer,
    Scout,
    Intimidator,
    ConArtist,
    Lookout,
    QuackDoctor,
    Mastermind,
    Plotter,
    Forger,
    Poisoner,
    Sniper,
    Pickpocket,
    Infiltrator,
    Locksmith,
    CatBurglar,
    Diplomat,
    Charm,
    Fence,
    Seducer,
    Quartermaster,
    MasterOfDisguise,
    Lieutenant
  }
}